version: '3.8'

services:
  voicemod:
    build: .
    environment:
      - VOICEMOD_DB_HOST=mysql
      - VOICEMOD_HOST=0.0.0.0
    ports:
      - 8080:8080

  mysql:
    image: mysql:8.0.22
    volumes:
      - mysql_data:/var/lib/mysql
      - ./localenv/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: voicemod
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    ports:
      - 3306:3306

volumes:
  mysql_data: