// Code generated by mockery v2.3.0. DO NOT EDIT.

package authmocks

import (
	mock "github.com/stretchr/testify/mock"
	session "github.com/vosgaust/voicemod-challenge.git/internal/domain/session"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

// GenerateSession provides a mock function with given fields: _a0
func (_m *SessionRepository) GenerateSession(_a0 session.Session) (session.Token, error) {
	ret := _m.Called(_a0)

	var r0 session.Token
	if rf, ok := ret.Get(0).(func(session.Session) session.Token); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(session.Token)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(session.Session) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
